import {editors} from './publication.mjs';
import {abiyRecord} from './articles/abiy-record.mjs';
const source = (id,title,url,publisher,date) => ({id,title,url,publisher,date});
const hrwPress=source('hrw-press','Ethiopia Shutters Key News Outlet','https://www.hrw.org/news/2026/02/25/ethiopia-shutters-key-news-outlet','Human Rights Watch','2026-02-25');
const hrwYear=source('hrw-2026','World Report 2026: Ethiopia — events of 2025','https://www.hrw.org/world-report/2026/country-chapters/ethiopia','Human Rights Watch','2026');
const amnesty=source('amnesty-cso','Ethiopia: Authorities must drop proposed changes to the CSO law','https://www.amnesty.org/en/documents/afr25/0185/2025/en/','Amnesty International','2025-08-18');
const bank=source('world-bank','World Bank Backs Ethiopia’s Reforms','https://www.worldbank.org/en/news/press-release/2024/07/30/world-bank-backs-ethiopia-s-reforms-to-promote-sustainable-and-inclusive-afe-growth','World Bank','2024-07-30');
const cso=source('hrw-cso','Ethiopia: Proposed Legal Changes Threaten Civil Society','https://www.hrw.org/news/2025/07/29/ethiopia-proposed-legal-changes-threaten-civil-society','Human Rights Watch','2025-07-29');
const claim=(text,...sourceIds)=>({type:'claim',text,sourceIds});
const opinion=text=>({type:'opinion',text,sourceIds:[]});
const heading=text=>({type:'heading',text,sourceIds:[]});
const base={byline:'The Unquiet Horn · Source desk',dateline:'DOCUMENT REVIEW',language:'en',translationStatus:'original',date:'2026-09-23',readMinutes:1};
const euEscalation=source('eu-september-2026','Statement on the situation in Northern Ethiopia','https://www.eeas.europa.eu/eeas/ethiopia-statement-spokesperson-situation-northern-ethiopia_en','European Union','2026-09-23');
const auEscalation=source('au-september-2026','AUC Chairperson calls for restraint and immediate de-escalation in Northern Ethiopia','https://www.au.int/en/pressreleases/20260923/chairperson-calls-restraint-and-immediate-de-escalation-northern-ethiopia','African Union','2026-09-23');
const unEscalation=source('un-september-2026','UN Secretary-General statement on Ethiopia','https://ethiopia.un.org/en/323246-un-secretary-general-statement-ethiopia','United Nations','2026-09-23');
const amnestyEscalation=source('amnesty-august-2026','Tigray residents at renewed risk as violence returns','https://www.amnesty.org/en/latest/news/2026/08/ethiopia-tigray-residents-at-renewed-risk-of-human-rights-violations-as-violence-returns-to-the-region/','Amnesty International','2026-08-03');
const eritreaContext=source('ap-eritrea-2026','Abiy’s vision of Ethiopia includes a seaport in Eritrea. Some see a looming conflict','https://apnews.com/article/01542a9d7954e0d2f94a7dbe7b00340e','Associated Press','2026-02-28');
export const articles=[
 abiyRecord,
 {
  ...base,
  slug:'abiy-ahmed-ethiopia-return-to-war',
  title:'Abiy Ahmed must answer for Ethiopia’s return to war',
  deck:'Renewed fighting in the north and the danger of confrontation with Eritrea demand political accountability. Our view: Abiy’s government must choose de-escalation over another military gamble.',
  category:'opinion-analysis', region:'Tigray', type:'Original opinion',
  date:'2026-09-24', byline:editors.names, authors:['daniel-asfaw','yohannes-asfaw'],
  dateline:'COMMENTARY · ETHIOPIA & THE HORN', readMinutes:4,
  sources:[euEscalation,auEscalation,unEscalation,amnestyEscalation,eritreaContext],
  sourceIds:['eu-september-2026','un-september-2026','ap-eritrea-2026'],
  pullquote:'A government’s first claim to legitimacy should be its ability to keep people alive, not its willingness to ask them for another sacrifice.',
  blocks:[
   opinion('Abiy Ahmed’s government should be judged by whether it can deliver a durable peace. We believe the renewed fighting in northern Ethiopia represents a profound failure of political leadership. The prime minister owes the country more than an explanation of who his enemies are. He owes it a credible way out of war.'),
   claim('On September 23, the European Union expressed concern about several drone strikes carried out by the Ethiopian National Defence Force in preceding weeks. The UN Secretary-General separately warned of intensified fighting in and around Tigray, with hostilities spreading into neighbouring areas. These statements describe an unfolding escalation, not simply a hypothetical danger.','eu-september-2026','un-september-2026'),
   opinion('That is why we are criticizing the government directly. A government’s first claim to legitimacy should be its ability to keep people alive, not its willingness to ask them for another sacrifice. Military capability cannot substitute for a political settlement that people can live with.'),
   heading('The government must answer for its own choices'),
   opinion('Our criticism concerns Abiy’s political responsibility and his government’s decisions. It is not a finding that he personally ordered every reported attack, or that one account settles who initiated each clash. Those questions require evidence. But uncertainty about a battlefield incident must not become an excuse to avoid questioning a government’s strategy.'),
   claim('Amnesty International had already warned on August 3 that renewed clashes between federal and Tigrayan forces exposed residents to further human rights violations. Its statement recalled grave abuses documented during the 2020–2022 conflict and called for access for independent monitors and humanitarian workers. The warning preceded the September escalation.','amnesty-august-2026'),
   opinion('We see a failure to treat civilian protection as the measure of success. The federal government should explain how renewed military action is supposed to secure a peace that negotiations cannot, what limits it places on that action, and how the public can independently examine the consequences. “Trust the leadership” is not an adequate answer when lives are at stake.'),
   heading('Criticizing Abiy does not excuse the TPLF'),
   claim('The African Union’s September 23 statement also criticized Tigrayan forces’ seizure of the airports in Mekelle, Axum and Shire, describing it as inconsistent with the Pretoria Agreement. It reported the detention of federal personnel and called for direct talks. Those actions belong in the record alongside the concerns about federal military operations.','au-september-2026'),
   opinion('We reject the idea that opposition to Abiy requires defending every decision of the TPLF or any other armed movement. Civilians should not have to earn protection by supporting the correct faction. The government’s opponents must answer for their conduct too. That does not relieve the prime minister of responsibility for the choices made by his own administration.'),
   heading('Eritrea must not become the next front'),
   claim('In February, Associated Press reported on Abiy’s push for sovereign access to the sea and the resulting fears of conflict with Eritrea. That report provides background to the regional risk; it does not establish that a new Ethiopia–Eritrea war has begun. In its September statement, the African Union called on Ethiopia’s neighbours to avoid steps that could intensify the crisis.','ap-eritrea-2026','au-september-2026'),
   opinion('Our position is straightforward: economic ambition cannot justify pursuing a port through force. Access to trade should be negotiated through workable agreements, not made into a test of national pride that ordinary Ethiopians and Eritreans might be asked to pay for with their lives.'),
   opinion('The danger we see is that the conflict in Tigray and hostility across the Eritrean border could reinforce each other, making restraint harder and drawing more people into the fighting. This is our assessment of the risk, not a claim that a wider regional war is inevitable. Abiy should make the peaceful limits of his government’s policy explicit and act consistently with them. Eritrea’s leadership should be held to the same standard of restraint.'),
   heading('What accountability should look like now'),
   opinion('The government should pursue an immediate, verifiable halt to escalation and return to direct negotiations. It should publish clear commitments on humanitarian access, allow independent scrutiny of alleged abuses, and give the public a concrete account of the steps it is taking toward peace. Political opponents should be able to challenge those choices without being treated as enemies of the country.'),
   claim('The UN’s September 23 statement calls for civilian protection, unhindered humanitarian access and renewed talks under the Pretoria framework. The EU also condemns strikes affecting humanitarian convoys. These are public demands against which the conduct of every party can be examined.','un-september-2026','eu-september-2026'),
   opinion('We want an Ethiopia in which political leadership is measured by the lives it protects and the disagreements it resolves. Abiy Ahmed’s government must be challenged when it falls short of that standard. Preventing another devastating war, and stopping the renewed fighting from spreading, should take precedence over the survival, prestige or ambitions of any leader.')
  ]
 },
 {...base,slug:'addis-standard-license-and-the-public-record',title:'A revoked license. An unanswered question of evidence.',deck:'Human Rights Watch’s February dispatch on Addis Standard sets out the regulator’s allegations and the newsroom’s response.',category:'press-freedom',region:'National',type:'Source briefing',sources:[hrwPress],sourceIds:['hrw-press'],blocks:[heading('The documented record'),claim('Human Rights Watch reported that Ethiopia’s Media Authority revoked Addis Standard’s operating license on February 24, 2026. This briefing describes that February report; it does not establish the outlet’s present licensing status.','hrw-press'),claim('According to HRW, the authority alleged repeated legal and ethical violations and harm to national interests, without identifying specific violations in its announcement. HRW also reported that editor-in-chief Yonas Kedir rejected the allegations and said the newsroom had received no formal notice of earlier violations or enforcement actions.','hrw-press'),heading('What remains unresolved'),opinion('A regulator’s allegation and a publisher’s denial are competing accounts. Evaluating the decision requires the underlying notices, evidence and any subsequent judicial record. This publication has not independently obtained those records.')],pullquote:'A regulator’s allegation and a publisher’s denial are competing accounts.'},
 {...base,slug:'ethiopia-2025-rights-record',title:'Reading Ethiopia’s rights record beyond a single conflict',deck:'HRW’s 2026 country chapter describes conflict and restrictions on civic space during 2025.',category:'human-rights',region:'Amhara',type:'Source briefing',sources:[hrwYear],sourceIds:['hrw-2026'],blocks:[heading('What the report covers'),claim('Human Rights Watch’s account of 2025 describes hostilities involving federal forces and armed groups in Amhara and parts of Oromia, and renewed instability in Tigray. It also describes restrictions on independent media and civil society. These are HRW’s findings, not new field reporting by this publication.','hrw-2026'),claim('The chapter reports civilian harm, displacement and restricted humanitarian access. Its allegations concern identified institutions and armed actors; they should not be attributed collectively to Ethiopia’s people or to an ethnic community.','hrw-2026'),opinion('Read the chapter’s linked evidence alongside its conclusions. A country overview provides context, but cannot establish responsibility for every individual incident.')]},
 {...base,slug:'civil-society-law-accountability',title:'Civil society oversight needs public scrutiny, too',deck:'Amnesty’s August 2025 statement challenges proposed changes to Ethiopia’s civil society law.',category:'politics-governance',region:'National',type:'Source briefing',sources:[amnesty,cso],sourceIds:['amnesty-cso'],blocks:[claim('Amnesty International called on Ethiopian authorities to abandon proposed amendments to the civil society law in a public statement dated August 18, 2025. The statement places the proposals in the context of restrictions on civic space.','amnesty-cso'),claim('Human Rights Watch separately reported that officials consulted government representatives and a selected group of nongovernmental organizations in June 2025 while gathering input on draft amendments.','hrw-cso'),opinion('The existence of a proposal is not evidence that it became law. Readers should check an enacted text, commencement date and later amendments before treating a draft provision as a current legal requirement.')]},
 {...base,slug:'what-budget-support-announcements-prove',title:'What a $1.5 billion financing announcement can—and cannot—tell us',deck:'The World Bank’s July 2024 announcement separates grant support from concessional credit.',category:'economy',region:'National',type:'Explainer',sources:[bank],sourceIds:['world-bank'],blocks:[claim('On July 30, 2024, the World Bank announced approval of an Ethiopian development policy operation comprising a $1 billion grant and $500 million in concessional credit. The Bank described goals including fiscal transparency and protection for vulnerable households.','world-bank'),opinion('Approval, disbursement and impact answer different questions. An announcement of financing does not itself demonstrate that households received support or that a reform achieved its stated goals.'),heading('Questions for follow-up reporting'),opinion('The next documents to seek are disbursement records, budget execution reports and independently assessed results. Coverage should compare the stated objectives with measurable outcomes, and distinguish the lender’s assessment from independent evidence.')]},
 {...base,slug:'verification-addis-standard-allegations',title:'License revocation: allegation is not a published finding',deck:'An evidence check of the regulatory claims described in HRW’s February 2026 dispatch.',category:'verification',region:'National',type:'Verification',sources:[hrwPress],sourceIds:['hrw-press'],blocks:[heading('The claim — attributed'),claim('HRW reported that the Media Authority accused Addis Standard of legal and ethical violations. The newsroom disputed the allegations.','hrw-press'),heading('The evidence available here'),claim('The HRW dispatch says the announcement did not specify the violations. It links to the authority’s statement. This check relies on HRW’s account; we have not independently authenticated the underlying statement.','hrw-press'),heading('Assessment: not established by this record'),opinion('The cited material establishes a dispute, not the truth of every allegation. No verdict of “true” or “false” is warranted on this limited record. A primary notice, specific examples, the publisher’s full response and any court ruling would allow a stronger assessment.')]},
 {...base,slug:'accountability-begins-with-an-auditable-record',title:'Accountability begins with a record readers can inspect',deck:'Editorial view: independent scrutiny should be testable, specific and open to correction.',category:'opinion-analysis',region:'National',type:'Analysis',byline:'The Unquiet Horn · Editorial perspective',sources:[cso],sourceIds:['hrw-cso'],blocks:[opinion('A watchdog publication should invite scrutiny of its own work. We believe every serious allegation should lead readers to its evidence, and every correction should leave a visible record.'),claim('HRW’s July 2025 account of proposed changes to Ethiopia’s civil society law describes a consultation involving selected organizations and government institutions.','hrw-cso'),opinion('Our view is that public access to draft texts, meaningful consultation and reviewable decisions are essential tests of accountable governance. That is an editorial judgment, not a finding about any individual’s criminal responsibility.'),opinion('Criticism must remain precise: name the institution, identify the action, and explain the evidence. A government, a country and an ethnic community are not interchangeable subjects.')],pullquote:'A watchdog publication should invite scrutiny of its own work.'},
 {...base,slug:'reading-conflict-reports-responsibly',title:'How to read a conflict report without losing the distinctions',deck:'A reader’s guide to the scope of HRW’s account of Amhara, Oromia and Tigray in 2025.',category:'conflict-security',region:'Tigray',type:'Explainer',sources:[hrwYear],sourceIds:['hrw-2026'],blocks:[claim('HRW’s 2026 Ethiopia chapter discusses federal forces, Fano, the Oromo Liberation Army and Eritrean troops in accounts of different places and events during 2025. These are distinct actors and contexts.','hrw-2026'),opinion('Ask three questions of each passage: who is making the allegation, what time and place does it cover, and what evidence is linked? A finding about one incident should not silently become a claim about an entire population.'),opinion('Keep dates attached to evidence. This is a reading guide to a historical reporting period, not a live security assessment. Follow the original report for details and limitations.')]}
];
export function validateArticle(a){
 if(!/^[a-z0-9-]+$/.test(a.slug)||!a.title||!a.deck||!a.byline||!a.sources?.length) throw Error(`Invalid article: ${a.slug}`);
 const ids=new Set(a.sources.map(s=>s.id));
 for(const s of a.sources) if(!/^https:\/\//.test(s.url)) throw Error('Sources must use HTTPS');
 if(!a.sourceIds?.length || a.sourceIds.some(id=>!ids.has(id))) throw Error(`Uncited deck: ${a.slug}`);
 for(const b of a.blocks){
  if(!['fact','claim','opinion','heading','quote','personal'].includes(b.type)) throw Error('Unknown evidence type');
  if(b.type==='personal'&&(!a.authors?.length||!b.attribution?.trim())) throw Error('Personal account requires named authors and attribution');
  if(['fact','claim','quote'].includes(b.type)&&!b.sourceIds?.length) throw Error(`Uncited factual block: ${a.slug}`);
  if(b.sourceIds?.some(id=>!ids.has(id))) throw Error('Unknown citation');
  if(b.type==='quote'&&!b.originalLanguage) throw Error('Quote requires original language');
 }
 return true;
}
articles.forEach(validateArticle);
