import {voiceSources,selectedPosts,selectVoiceReports,embedURL} from './voices.mjs';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=value=>{try{const url=new URL(value);return ['https:','http:'].includes(url.protocol)&&!url.username&&!url.password?esc(url.href):'#';}catch{return '#';}};
const date=value=>{if(value===null||value===undefined||String(value).trim()==='')return 'Date unavailable';const parsed=new Date(value);return Number.isNaN(parsed.getTime())?'Date unavailable':new Intl.DateTimeFormat('en',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(parsed);};
const external=(url,label)=>`<a href="${safeURL(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} <span aria-hidden="true">↗</span></a>`;
function sourceRow(source,statuses){
 const status=statuses.find(s=>s.id===source.feedId);
 const facebookLink=source.links.find(link=>{try{return new URL(link.url).hostname==='www.facebook.com';}catch{return false;}});
 const pageEmbed=facebookLink&&embedURL(facebookLink.url,{page:true});
 return `<article class="voice-source"><div class="eyebrow">${source.feedId?'NEWSROOM & SOCIAL CHANNELS':'SOCIAL CHANNELS'}</div><h3 translate="no">${esc(source.name)}</h3><p>${esc(source.description)}</p><nav class="voice-links" aria-label="${esc(source.name)} links">${source.links.map(link=>external(link.url,link.label)).join('')}</nav>${pageEmbed?`<div class="voice-embed" data-social-post><p>Optional Facebook page preview, hosted by Facebook. Availability and sign-in requirements may vary. Loading connects to Facebook; its privacy and cookie policies apply.</p><button class="button" type="button" data-load-post data-embed-url="${safeURL(pageEmbed)}" data-i18n-title="Facebook page preview" data-i18n-loading="Loading Facebook page…" data-i18n-loaded="Page preview requested. If unavailable or sign-in is required, use the Facebook link above." data-i18n-error="The preview could not load. Use the Facebook link above." data-i18n-retry="Retry loading Facebook page">Load Facebook page ↗</button><p class="voice-embed-status" role="status" aria-live="polite"></p><div class="voice-embed-frame"></div></div>`:''}${source.feedId?`<p class="voice-status"><span class="status-dot ${status?.status==='ok'?'ok':''}"></span>${status?.status==='ok'?'Feed connected':status?'Feed unavailable — cached reports may remain':'Awaiting first feed fetch'}${status?.lastSuccess?`<span>Last successful fetch: ${date(status.lastSuccess)}</span>`:''}</p>`:'<p class="voice-status">Profile links · posts are selected separately</p>'}</article>`;
}
function reportsList(reports){
 return reports.length?`<ol class="voice-report-list">${reports.map(item=>`<li><div class="field-meta"><span translate="no">${esc(item.source)}</span><time>${date(item.date)}</time></div><h3>${external(item.link,item.title)}</h3>${item.summary?`<p>${esc(item.summary)}</p>`:''}<span class="voice-report-credit">External report · read at the publisher</span></li>`).join('')}</ol>`:'<div class="voice-empty"><h3>No reports cached yet.</h3><p>Use the newsroom links to read their latest coverage. Reports will appear here after a successful feed update.</p></div>';
}
function selectedPost(post){
 const source=voiceSources.find(item=>item.id===post.sourceId);
 const embed=embedURL(post.url);
 return `<article class="voice-post"><div class="eyebrow"><span translate="no">${esc(post.platform)}</span><span>SELECTED LINK</span></div><h3 translate="no">${esc(source?.name||post.sourceId)}</h3><p>${esc(post.label)}</p><div class="voice-post-original">${external(post.url,`Open selected post on ${post.platform}`)}</div>${embed?`<div class="voice-embed" data-social-post><p>Loading this post connects to ${esc(post.platform)}. Its privacy and cookie policies apply.</p><button class="button" type="button" data-load-post data-embed-url="${safeURL(embed)}" data-i18n-title="Selected social post" data-i18n-loading="Loading post…" data-i18n-loaded="Post requested. If it is unavailable or asks you to sign in, use the original link above." data-i18n-error="This post could not load. Use the original link above." data-i18n-retry="Retry loading post">Load post ↗</button><p class="voice-embed-status" role="status" aria-live="polite"></p><div class="voice-embed-frame"></div></div>`:''}</article>`;
}
export function renderVoices({lang='en',fieldItems=[],statuses=[],compact=false}={}){
 const reports=selectVoiceReports(fieldItems).slice(0,compact?3:12);
 if(compact)return `<section class="voices-preview" aria-labelledby="voices-preview-title"><div class="section-heading"><h2 id="voices-preview-title">Sources & voices</h2><a class="text-link" href="/${esc(lang)}/voices">Explore the sources ↗</a></div><div class="voices-preview-grid"><div class="voices-preview-intro"><span class="section-label">BEYOND OUR PAGES</span><p>Follow the reporting.<br>Go to the source.</p><div class="voices-preview-names">${voiceSources.slice(0,2).map(source=>`<div><strong translate="no">${esc(source.name)}</strong><nav class="voice-links" aria-label="${esc(source.name)} links">${source.links.map(link=>external(link.url,link.label)).join('')}</nav></div>`).join('')}</div><p class="voice-disclosure">External reporting and social accounts. Inclusion is not independent verification of a claim or a reporter’s location.</p></div><div>${reportsList(reports)}</div></div></section>`;
 return `<section class="voices-page"><header class="listing-header"><span class="eyebrow">FOLLOW THE REPORTING</span><h1>Sources & voices</h1><p>Ethiopian newsrooms, journalists and the original accounts behind the headlines.</p></header><div class="voices-editor-note"><span class="section-label">READ WITH CONTEXT</span><p>These are external publications and social accounts. Inclusion does not verify each claim or establish a reporter’s location. Visit the original source for its evidence, updates and corrections.</p></div><div class="voices-columns"><section class="voices-reports" aria-labelledby="voice-reports-title"><div class="section-heading"><h2 id="voice-reports-title">From the newsrooms</h2><span>ATTRIBUTED. LINKED.</span></div><p class="voice-section-intro">Headlines and excerpts from selected publishers’ feeds. Updates are scheduled about every 30 minutes and may be delayed.</p>${reportsList(reports)}<p class="voice-disclosure">Connection status describes feed availability, not the accuracy of a report. When a source is unavailable, cached reports may be stale.</p></section><aside class="voices-directory" aria-labelledby="voice-directory-title"><div class="section-label">THE SOURCE DIRECTORY</div><h2 id="voice-directory-title">Read them directly.</h2>${voiceSources.map(source=>sourceRow(source,statuses)).join('')}</aside></div><section class="voices-social" aria-labelledby="voice-social-title"><div class="section-heading"><h2 id="voice-social-title">Selected social posts</h2><span>OPEN THE ORIGINAL</span></div><p class="voice-section-intro">A selection of links, not an automatically imported social timeline. These posts have not been independently reviewed by The Unquiet Horn. Profile links above take you directly to each account.</p>${selectedPosts.length?`<div class="voice-posts">${selectedPosts.map(selectedPost).join('')}</div>`:'<div class="voice-empty"><p>No individual posts have been selected yet. Follow the accounts above for their latest updates.</p></div>'}<p class="voice-disclosure">No individual Instagram posts have been selected yet. Selected public Facebook or Instagram posts can appear here when their links are added; original links remain available if an embedded post cannot load.</p></section></section>`;
}
